/*
 * DetailTableTypePanel.java
 *
 * Created on December 2, 2003, 8:40 AM
 */

package org.jax.mgi.mtb.jSql.windows;

import org.jax.mgi.mtb.jSql.windows.*;
import org.jax.mgi.mtb.jSql.dialogs.*;
import org.jax.mgi.mtb.jSql.utils.*;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.*;
import java.io.*;
import java.sql.*;
import java.util.*;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.text.*;


import org.jax.mgi.mtb.jSql.*;

/**
 *
 * @author  mjv
 */
public class DetailTableTypePanel extends JPanel {
    private jSql app = null;
    private Connection conn = null;
    private SortableTableModel sortableTableModel = null;
    private TableSorter tableSorter = null;
    private String catalog = null;
    private String schema = null;
    private String query = null;
    private ResultSet rs = null;
    
    /** Creates new form DetailTableTypePanel */
    public DetailTableTypePanel(jSql app, /*, String catalog, String schema, String table, */Connection conn, ResultSet rs) {
        super();
        this.app = app;
        //this.catalog = catalog;
        //this.schema = schema;
        //this.table = table;
        this.conn = conn;
        initComponents();
        this.rs = rs;
        this.query = null;
        gatherData();
    }
    
    public DetailTableTypePanel(jSql app, /*, String catalog, String schema, String table, */Connection conn, String query) {
        super();
        this.app = app;
        //this.catalog = catalog;
        //this.schema = schema;
        //this.table = table;
        this.conn= conn;
        initComponents();
        this.query = query;
        this.rs = null;
        gatherData();
    }
    

    public void gatherData() {
        //Connection conn = app.getConnection(connectionId);
        try {
            jScrollPane1.getViewport().remove(tblTableColumns);
            sortableTableModel = new SortableTableModel(conn);
            sortableTableModel.setMaxRows(500);
            
            tableSorter = new TableSorter(sortableTableModel);
            
            //DatabaseMetaData dmd = conn.getMetaData();
            //ResultSet rs = dmd.getColumns(catalog, schema, table, null);
            if (rs != null) {
                //System.out.println("USING RS");
                sortableTableModel.executeQuery(rs);
            } else {
                //System.out.println("USING QUERY");
                sortableTableModel.executeQuery(query);
            }
            
            tblTableColumns = new JTable(tableSorter);
            tblTableColumns.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            SortButtonRenderer renderer = new SortButtonRenderer();
            TableColumnModel model = tblTableColumns.getColumnModel();
            TableModel tm = tblTableColumns.getModel();
            int n = tm.getColumnCount();
            for (int i = 0; i < n; i++) {
                model.getColumn(i).setHeaderRenderer(renderer);
                FontMetrics fm = tblTableColumns.getFontMetrics(tblTableColumns.getFont());
                TableColumnModel columnModel = tblTableColumns.getColumnModel();
                TableColumn column = columnModel.getColumn(i);
                int width = SwingUtilities.computeStringWidth(fm, tm.getColumnName(i) + "            ");
                //then to set the width of your column:
                column.setPreferredWidth(width);
            }

            JTableHeader header = tblTableColumns.getTableHeader();
            header.addMouseListener(new HeaderListener(header, renderer));
            //jeditSqlMessages.setText("");
            jScrollPane1.getViewport().add(tblTableColumns, null);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            //app.returnConnection(connectionId, conn);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTableColumns = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tblTableColumns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTableColumns);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTableColumns;
    // End of variables declaration//GEN-END:variables
    
}
