/*
 * AboutDialog.java
 */

package org.jax.mgi.mtb.jSql.dialogs;

import java.awt.Frame;
import java.util.Enumeration;
import java.util.Properties;
import javax.swing.JDialog;

/**
 * <p>The <b>AboutDialog</b> class extends the JDialog class
 * and displays the java properties for the system.</p>
 *
 * @author Matthew J. Vincent
 * @version $Revision: 1.1 $ $Date: 2008/08/08 13:37:54 $
 */
public class AboutDialog extends JDialog {
    
    // ----------------------------------------------------------- Constructors

    /** 
     * Creates new form AboutDialog.
     *
     * @param parent A Frame object representing the parent container
     * @param modal True for a modal dialog, false otherwise
     */
    public AboutDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initialize();
    }
    
    // -------------------------------------------------------- Private Methods

    /**
     * Custom initialization of the components.
     */
    private void initialize() {
        String FILE_SEPARATOR = System.getProperty("file.separator");
        String PROPERTIES_FILE = ".jSql_properties";
        String USER_HOME = System.getProperty("user.home");
        String propString = "";
        textPaneProperties.setText(textPaneProperties.getText()+
            "\r\nProperties File=" + USER_HOME+FILE_SEPARATOR+PROPERTIES_FILE + 
            "\r\n\r\n");

        // enumerate all the system properties
        Properties props = System.getProperties();
        Enumeration e = props.propertyNames(); 
        
        while (e.hasMoreElements()) {
            String propName = (String)e.nextElement();
            String propValue = (String)props.get(propName);
            propString = propString + propName + "=" + propValue + "\r\n";
        }
        
        textPaneProperties.setText(textPaneProperties.getText() + propString);
        textPaneProperties.setCaretPosition(0);
    }
    
    /** 
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        panelMain = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        buttonLogo = new javax.swing.JButton();
        panelProperties = new javax.swing.JPanel();
        scrollPaneProperties = new javax.swing.JScrollPane();
        textPaneProperties = new javax.swing.JTextPane();

        setTitle("About jSql");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        panelMain.setLayout(new java.awt.GridLayout(2, 1));

        buttonLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jax/mgi/mtb/jSql/resources/jSql.gif")));
        buttonLogo.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelLogo.add(buttonLogo);

        panelMain.add(panelLogo);

        panelProperties.setLayout(new java.awt.BorderLayout());

        textPaneProperties.setText("jSql 2.0\nWritten by Matthew Vincent\nmjv@informatics.jax.org\n\n");
        scrollPaneProperties.setViewportView(textPaneProperties);

        panelProperties.add(scrollPaneProperties, java.awt.BorderLayout.CENTER);

        panelMain.add(panelProperties);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /**
     * Closes the dialog.
     *
     * @param evt WindowEvent object
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    // ----------------------------------------------------- Instance Variables
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogo;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelProperties;
    private javax.swing.JScrollPane scrollPaneProperties;
    private javax.swing.JTextPane textPaneProperties;
    // End of variables declaration//GEN-END:variables
    
}
