/*
 * ExportDialog.java
 *
 * Created on December 3, 2003, 10:26 AM
 */

package org.jax.mgi.mtb.jSql.dialogs;
import java.awt.*;

import java.io.File;
import java.io.RandomAccessFile;
import javax.swing.JFileChooser;
import javax.swing.table.TableModel;
import java.awt.datatransfer.*;
import javax.swing.JOptionPane;
import javax.swing.*;
import org.jax.mgi.mtb.jSql.windows.*;

/**
 *
 * @author  mjv
 */
public class ExportDialog extends javax.swing.JDialog {
    
    SqlQueryFrame sqlF = null;
    DatabaseBrowserFrame browserF = null;
    
    /** Creates new form ExportDialog */
    public ExportDialog(java.awt.Frame parent, SqlQueryFrame sqlF, DatabaseBrowserFrame browserF, boolean modal) {
        super(parent, modal);
        initComponents();
/*        
        if (parent instanceof SqlQueryFrame) {
            sqlF = (SqlQueryFrame)parent;
        } else if (parent instanceof DatabaseBrowserFrame) {
            browserF = (DatabaseBrowserFrame)parent;
        }
 */
        this.sqlF = sqlF;
        this.browserF = browserF;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        radioButtonComma = new javax.swing.JRadioButton();
        radioButtonTab = new javax.swing.JRadioButton();
        radioButtonHtml = new javax.swing.JRadioButton();
        radioButtonOther = new javax.swing.JRadioButton();
        txtOther = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        radioButtonFile = new javax.swing.JRadioButton();
        txtFileName = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        radioButtonClipboard = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        btnExport = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        progressBarStatus = new javax.swing.JProgressBar();

        setTitle("jSql Export");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Export Delimiters"));
        radioButtonComma.setSelected(true);
        radioButtonComma.setText("Comma");
        buttonGroup1.add(radioButtonComma);
        jPanel2.add(radioButtonComma, new java.awt.GridBagConstraints());

        radioButtonTab.setText("Tab");
        buttonGroup1.add(radioButtonTab);
        jPanel2.add(radioButtonTab, new java.awt.GridBagConstraints());

        radioButtonHtml.setText("Html");
        buttonGroup1.add(radioButtonHtml);
        jPanel2.add(radioButtonHtml, new java.awt.GridBagConstraints());

        radioButtonOther.setText("Other");
        buttonGroup1.add(radioButtonOther);
        jPanel2.add(radioButtonOther, new java.awt.GridBagConstraints());

        txtOther.setMinimumSize(new java.awt.Dimension(20, 20));
        txtOther.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel2.add(txtOther, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jPanel3.setBorder(new javax.swing.border.TitledBorder("Export Destination"));
        radioButtonFile.setSelected(true);
        radioButtonFile.setText("File");
        buttonGroup2.add(radioButtonFile);
        jPanel4.add(radioButtonFile);

        txtFileName.setMinimumSize(new java.awt.Dimension(300, 20));
        txtFileName.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel4.add(txtFileName);

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        jPanel4.add(btnBrowse);

        radioButtonClipboard.setText("Clipboard");
        buttonGroup2.add(radioButtonClipboard);
        jPanel4.add(radioButtonClipboard);

        jPanel3.add(jPanel4);

        jPanel1.add(jPanel3);

        jPanel5.setLayout(new java.awt.BorderLayout());

        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        jPanel5.add(btnExport, java.awt.BorderLayout.NORTH);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jPanel5.add(btnCancel, java.awt.BorderLayout.CENTER);

        jPanel5.add(progressBarStatus, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    // This method writes a string to the system clipboard.
    // otherwise it returns null.
    public void setClipboard(String str) {
        StringSelection ss = new StringSelection(str);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(ss, null);
    }    
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // Add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // Add your handling code here:
        export();
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // Add your handling code here:
        JFileChooser dlg = new JFileChooser();

        dlg.showOpenDialog(this);

        if (dlg.getSelectedFile() != null) {
            txtFileName.setText(dlg.getSelectedFile().toString());
        }        
    }//GEN-LAST:event_btnBrowseActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    public void export() {
        try {
            JTable t = sqlF.getTable();
            TableModel tm = t.getModel();

            String dataDelim = null;
            String lineStartDelim = null;
            String lineEndDelim = null;
            StringBuffer sb = new StringBuffer();

            if (radioButtonComma.isSelected()) {
                // CSV
                dataDelim = "\t";
                lineStartDelim = "";
                lineEndDelim = "\n";
            } else if (radioButtonTab.isSelected()) {
                // TAB
                dataDelim = ",";
                lineStartDelim = "";
                lineEndDelim = "\n";
            } else if (radioButtonHtml.isSelected()) {
                // HTML
                dataDelim = "</td><td>";
                lineStartDelim = "<tr><td>";
                lineEndDelim = "</td></tr>\n";
                sb.append("<html><body bgcolor=white><table border=1>\n");
            } else if (radioButtonOther.isSelected()) {
                // other
                dataDelim = txtOther.getText();
                lineStartDelim = "";
                lineEndDelim = "";
            }

            sb.append(lineStartDelim);

            for (int header = 0; header < tm.getColumnCount(); header++) {
                sb.append(tm.getColumnName(header));

                if (header != (tm.getColumnCount() - 1)) {
                    sb.append(dataDelim);
                }
            }

            sb.append(lineEndDelim);

            for (int row = 0; row < tm.getRowCount(); row++) {
                sb.append(lineStartDelim);

                for (int column = 0; column < tm.getColumnCount(); column++) {

                    Object val = tm.getValueAt(row, column);

                    sb.append(val);

                    if (column != (tm.getColumnCount() - 1)) {
                        sb.append(dataDelim);
                    }
                }

                sb.append(lineEndDelim);
            }

            if (radioButtonHtml.isSelected()) {
                // HTML
                sb.append("\n</table></body></html>");
            }

            if (radioButtonFile.isSelected()) {
                if ((txtFileName.getText() == null) || (txtFileName.getText().equals(""))) {
                    handleException(new Exception("Please select a file to export the data to."));
                    return;
                }

                File exportFile = new File(txtFileName.getText());
                RandomAccessFile raFile = new RandomAccessFile(exportFile, "rw");

                raFile.writeBytes(sb.toString());
                raFile.close();
            } else {
                setClipboard(sb.toString());
            }
        } catch (Exception exc) {
            handleException(exc);
            // exc.printStackTrace();
        }
    }
    
    public void handleException(Exception e) {
        JOptionPane.showMessageDialog(null, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnExport;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar progressBarStatus;
    private javax.swing.JRadioButton radioButtonClipboard;
    private javax.swing.JRadioButton radioButtonComma;
    private javax.swing.JRadioButton radioButtonFile;
    private javax.swing.JRadioButton radioButtonHtml;
    private javax.swing.JRadioButton radioButtonOther;
    private javax.swing.JRadioButton radioButtonTab;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtOther;
    // End of variables declaration//GEN-END:variables
    
}
